name: Deploy Backend

on:
  push:
    branches: [ main ]  # adjust this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build -t backend-app ./backend
    
    - name: Run Docker container
      env:
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: |
        docker run -d -p 8000:8000 \
          -e ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY \
          backend-app